### ISSUE TITLE
Cannot run the test suite

### ISSUE THREAD

**Issue by karussell** [geocoders/geocoder-tester#19]
Could you explain how one needs to install python3 with virtualenvs?
I fear I messed something up as I currently get:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config.py", line 379, in _importconftest
    mod = conftestpath.pyimport()
  File "/usr/local/lib/python2.7/dist-packages/py/_path/local.py", line 662, in pyimport
    __import__(modname)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/py/_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "/home/peter/Documents/quell/examples/geocoder-tester/conftest.py", line 8, in <module>
    from geocoder_tester.base import assert_search, CONFIG
  File "/home/peter/Documents/quell/examples/geocoder-tester/geocoder_tester/base.py", line 57
SyntaxError: Non-ASCII character '\xc2' in file /home/peter/Documents/quell/examples/geocoder-tester/geocoder_tester/base.py on line 57, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
ERROR: could not load /home/peter/Documents/quell/examples/geocoder-tester/conftest.py
```

**Comment by yohanboniface** [comment]
> Could you explain how one needs to install python3 with virtualenvs?

Well, you need to install python 3 on your system, along python 2.7 if you have it. The virtualenv is for installing python package out of your system.

Which OS are you running?

**Comment by karussell** [comment]
My problem is that it is an 16.04 Linux with python 2.7 and so some tools from apt rely on python 2.7 and I did not find a way to use python3 on my system without deinstalling 2.7.

**Comment by yohanboniface** [comment]
Humm, isn't Ubuntu 16.04 shipped with both Python 3 and Python 2 pre-installed? What do you have id you type `python3` on your terminal?

**Comment by karussell** [comment]
Ah, ok. This works ... so how do I pick the correct python when executing .py files :) ?

**Comment by karussell** [comment]
(And what about the pip requirements?)

**Comment by yohanboniface** [comment]
> Ah, ok. This works ... so how do I pick the correct python when executing .py files :) ?

This is how I'd do it on a fresh Ubuntu server:

    # You can store the venv where ever you want
    python3 -m venv path/of/your/choice
    # each time you want to activate the virtualenv
    source path/of/your/choice/bin/activate
    # Once the venv is active,  install dependencies
    pip install -r path/to/geocoder-tester/requirements.txt
    # And then
    py.test -h

You may use higher level tools (like mkvirtualenv or pyenv) but that recipe is simple enough for baby steps imho.

**Comment by karussell** [comment]
Thanks, this worked. How do I run all tests?

```
py.test --api-url 'http://photon.komoot.de/api?'
==================== test session starts ====================
platform linux -- Python 3.5.2, pytest-3.2.3, py-1.4.34, pluggy-0.4.0 -- /path/to../.python-venv/bin/python3
cachedir: .cache
rootdir: /path../geocoder-tester, inifile: pytest.ini
collected 0 items                                                                                                                                     

=================== no tests ran in 0.01 seconds =============
```

**Comment by yohanboniface** [comment]
You need to run py.test from the root for geocoder-tester, is it the case?

**Comment by karussell** [comment]
Sorry, I messed up the repo when I tried the python3 stuff. Now this works.
