### ISSUE TITLE
POI - add an airport dataset

### ISSUE THREAD

**Issue by nlehuby** [geocoders/geocoder-tester#26]
Would it be ok to add the airport dataset from [OpenFlight](https://openflights.org/data.html) as a POI dataset ?

It is made available under the ODbL license, so I guess we will need to add a license file somewhere in our repo to explicit that.

**Comment by yohanboniface** [comment]
Sounds good.
Just make sure to add it under a `/poi/` subfolder, so it's get tagged automatically as poi, and it can be skipped easily for those who don't have pois in their data.

Not sure about the license impact though. Maybe add a licence in the same folder as the dataset?

**Comment by nlehuby** [comment]
this is a worldwide dataset. Do I add a poi subfolder inside the world folder ?

**Comment by yohanboniface** [comment]
I'd say yes :)

**Comment by nlehuby** [comment]
done in PR #29
