### ISSUE TITLE
Interrupted: 1 errors during collection - but no additional info

### ISSUE THREAD

**Issue by marcosox** [geocoders/geocoder-tester#31]
After following the steps in the readme (with data successfully imported from local nominatim instance), a generic error is shown but no context or details about what actually is the error.

    (venv-geocode-tester) user@debian:~/geocoder-tester/geocoder_tester$ py.test --api-url http://localhost:2322/api/
    
    [a line of equal signs omitted because it messes up markdown]
    platform linux -- Python 3.5.3, pytest-3.3.2, py-1.5.2, pluggy-0.6.0 -- /home/user/venv-geocode-tester/bin/python3
    cachedir: ../.cache
    rootdir: /home/user/geocoder-tester, inifile: pytest.ini
    collected 20361 items / 1 errors                                                                                                                                                                                  
    [exclamation points omitted because they mess up markdown] Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    
    [a line of equal signs omitted because it messes up markdown]

Any insight about this message?

**Comment by yohanboniface** [comment]
Weird. This seems like an error while collecting the test cases.
Can you try with `--verbose` of `--fulltrace` or `--debug`, and this last case you should have more details in a `pytestdebug.log` file.

**Comment by nlehuby** [comment]
The PR #35 may fix this.

**Comment by marcosox** [comment]
Thanks, the PR fixes the error. I was testing an italian dataset indeed.
