### ISSUE TITLE
Compare second hit

### ISSUE THREAD

**Issue by karussell** [geocoders/geocoder-tester#33]
Is it possible to compare not only the first but also the second hit? For certain requests like search "Berlin" with a certain location bias, the first result should be the city and the second should be the street "Berliner Str" of another city, which is the result of the location bias. Is this currently possible?

**Comment by yohanboniface** [comment]
Yes, you can define how much results will be considered with the `limit` parameter. This needs to be set test case by test case, see for example https://github.com/geocoders/geocoder-tester/blob/master/geocoder_tester/world/france/iledefrance/test_fuzzy.csv

**Comment by karussell** [comment]
Ah, and always the **last** hit will be picked?

**Comment by karussell** [comment]
Cool, works for me!
